services:
  # Malware Scanner used from user panel
  clamav:
    image: clamav/clamav:latest
    container_name: clamav
    volumes:
      - /home:/home
      - ./clamav-db:/var/lib/clamav
    restart: unless-stopped
    environment:
      - CLAMD_STARTUP_DELAY=30
    mem_limit: 1g
    cpus: 1.0
